# Generated by Django 5.2 on 2025-04-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('calculation', 'Calculation'), ('database', 'Database')], max_length=15)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='calc_type',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='content',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('ok', 'Ok'), ('fail', 'Fail')], default='running', max_length=7),
        ),
        migrations.AddField(
            model_name='calculation',
            name='config',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calculations', to='kmengine.config'),
        ),
    ]
