# Generated by Django 5.2 on 2025-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmengine', '0002_config_remove_calculation_calc_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calculation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['running', 'ok', 'fail'])), name='calculation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='config',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['calculation', 'database'])), name='config_type_valid'),
        ),
    ]
