# Generated by Django 5.2 on 2025-04-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmengine', '0003_calculation_calculation_status_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='config',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='kmengine.config'),
        ),
    ]
