# Generated by Django 5.2 on 2025-05-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kmengine", "0007_script_created_at_script_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="input",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="calculation",
            name="output",
            field=models.TextField(default=""),
        ),
    ]
